language: groovy
jdk: oraclejdk8

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script: gradle check integrationTest

after_success:
  - bash <(curl -s https://codecov.io/bash)
