sudo: required # for Docker
language: groovy
jdk: oraclejdk8

services:
  - docker

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

install: docker/postgresql/build_run.sh 6666

script:
  # Test using in-memory HSQLDB
  - gradle integrationTest
  # Test with a dockerized PostgreSQL (need to remap the port
  # because of https://github.com/travis-ci/travis-ci/issues/4744)
  - gradle -d clean integrationTest -Dspring.profiles.active=local,travis

after_success:
  # Install codeconv code coverage integration
  - bash <(curl -s https://codecov.io/bash)
