# Default configuration for local development
server:
    port: 8081

logging:
  level:
    io.github.lhanson: TRACE

---

# Local profile, uses PostgreSQL but starts from scratch each time
# Assumes the database has been set up ala docker/postgresql/init-db.sh
spring:
  profiles: local
  datasource:
    platform: postgresql-from-scratch
    url: jdbc:postgresql:timneh
    username: timneh
    password:
    driver-class-name: org.postgresql.Driver

---

# Profile for running on Travis CI, where we'll be using a dockerized
# instance of PostgreSQL, but need to work around the inability to
# use port 5432 (https://github.com/travis-ci/travis-ci/issues/4842)
spring:
  profiles: travis-ci
  datasource:
    port: 6666
