# Default configuration for local development
server:
    port: 8081

spring:
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%5p) %-40.40logger{39} %clr(:){faint} %m%n%wEx"
  level:
    io.github.lhanson: TRACE
    #org.springframework.security: DEBUG

jwt:
  token:
    secret: sssshhhh!

---

# Local profile, uses PostgreSQL but starts from scratch each time
# Assumes the database has been set up ala docker/postgresql/init-db.sh
spring:
  profiles: local
  datasource:
    platform: postgresql-from-scratch
    url: jdbc:postgresql://localhost:5432/timneh


---

# Profile for running on Travis CI, where we'll be using a dockerized
# instance of PostgreSQL, but need to work around the inability to
# use port 5432 (https://github.com/travis-ci/travis-ci/issues/4842)
spring:
  profiles: travis-ci
  datasource:
    platform: postgresql-from-scratch
    url: jdbc:postgresql://localhost:6666/timneh
