# Default configuration for local development
server:
    port: 8081

logging:
  level:
    io.github.lhanson: TRACE

---

# Local profile, uses PostgreSQL but starts from scratch each time
# Assumes the database has been set up ala docker/postgresql/init-db.sh
spring:
  profiles: local
  datasource:
    platform: postgresql-from-scratch
    url: jdbc:postgresql:timneh
    username: timneh
    password:
    driver-class-name: org.postgresql.Driver
