# Baseline configuration.
# Override in an environment-specific configuration
server:
    port: 8080

spring:
  datasource:
    username: timneh
  output:
    ansi:
      enabled: ALWAYS

logging:
  pattern:
    console: "%clr(%5p) %-40.40logger{39} %clr(:){faint} %m%n%wEx"
  level:
    root: WARN
    io.github.lhanson: INFO

jwt:
  token:
    # NOTE: set the 'secret' property in an external configuration for actual deployments.
    # See: https://docs.spring.io/spring-boot/docs/current/reference/html/boot-features-external-config.html
    header: Authorization
    expiration: 604800
  routes:
    authentication: auth
    refresh: refresh
    protected: protected


---

# Local profile, uses PostgreSQL but starts from scratch each time
# Assumes the database has been set up ala docker/postgresql/init-db.sh
spring:
  profiles: local
  datasource:
    platform: postgresql-from-scratch
    url: jdbc:postgresql://localhost:5432/timneh


---

# Profile for running on Travis CI, where we'll be using a dockerized
# instance of PostgreSQL, but need to work around the inability to
# use port 5432 (https://github.com/travis-ci/travis-ci/issues/4842)
spring:
  profiles: travis-ci
  datasource:
    platform: postgresql-from-scratch
    url: jdbc:postgresql://localhost:6666/timneh
